dot_o = ->(file) {"#{File.basename file}.o"}

import '../rakelib/gtest.rake'
namespace :test do
  build_path = Pathname 'test'
  lib_path   = Pathname '../libraries'
  test_sources  = %w[round_test.cc interrupt_button_test.cc]
  sources       = %w[interrupt_button.cpp poll_button.cpp].map {|source| lib_path.join source }

  for source in test_sources
    file build_path.join(dot_o[source]) => "test/#{source}" do |t|
      sh "c++ -c -I. -Itest -I../libraries -I../gtest/include #{t.prerequisites.first} -o #{t.name}"
    end
  end

  for source in sources
    file build_path.join(dot_o[source]) => source do |t|
      sh "c++ -c -Itest #{t.prerequisites.first} -o #{t.name}"
    end
  end

  dependencies = (sources + test_sources).map {|source| build_path.join dot_o[source] }
  file build_path.join('test') => dependencies + %i[gtest] do |t|
    sh "c++ -o #{t.name} #{dependencies.join ' '} #$gtest_lib"
  end

  task all: build_path.join('test') do |t|
    sh "./#{t.prerequisites.first}"
  end

  task :clean do
    sh "rm #{dependencies.join ' ' } #{build_path.join 'test' }"
  end
end

task test: 'test:all'
arduino_path = Pathname '/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino'
core_path = arduino_path.join 'cores/arduino'

CXX_FLAGS = <<-FLAGS.gsub "\n", ' '
  -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p
  -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105
  -I#{arduino_path.join 'cores/arduino' }
  -I#{arduino_path.join 'variants/standard' }
FLAGS

sources = %w[pressit.cpp pin.cpp interrupt_button.cpp]
for source in sources
  file dot_o[source] => source do |t|
    sh "avr-gcc #{CXX_FLAGS} -c #{t.prerequisites.first}"
  end
end

core_sources = %w[WInterrupts.c wiring.c wiring_analog.c wiring_digital.c
    wiring_pulse.c wiring_shift.c CDC.cpp HardwareSerial.cpp HID.cpp
    IPAddress.cpp main.cpp new.cpp Print.cpp Stream.cpp Tone.cpp USBCore.cpp
    WMath.cpp WString.cpp avr-libc/malloc.c avr-libc/realloc.c].map { |file| core_path.join(file) }

for core_source in core_sources
  file dot_o[core_source.basename] => core_source do |t|
    sh "avr-gcc #{CXX_FLAGS} -c #{t.prerequisites.first}"
  end
end

file 'core.a' => core_sources.map {|source| dot_o[source.basename] } do |t|
  sh "avr-ar rcs #{t.name} #{ t.prerequisites.join ' ' }"
end

file 'pressit.elf' => sources.map(&dot_o) + %w[core.a] do |t|
  sh "avr-gcc -Os -Wl,--gc-sections -L. -lm -mmcu=atmega328p -o #{t.name} #{t.prerequisites.join ' '}"
end

file 'pressit.hex' => 'pressit.elf' do |t|
  sh "avr-objcopy -O ihex -R .eeprom #{t.prerequisites.first} #{t.name}"
end

task build: 'pressit.hex'
task default: :build

task upload: :build do |t|
  port = Dir['/dev/tty.usbmodem*'].first or raise "plug the arduino in!"
  sh "avrdude -v -v -pm328p -carduino -P #{port} -U flash:w:pressit.hex:i"
end

task :clean do
  sh "rm *.o *.d *.a *.hex *.elf"
end
