namespace :test do
  gtest_sources = %w[gtest-all gtest_main]
  test_sources  = %w[round_test interrupt_button_test]
  sources       = %w[interrupt_button poll_button]
  dot_o         = ->(file) {"#{file}.o"}

  for source in gtest_sources
    file dot_o[source] => "../gtest/src/#{source}.cc" do |t|
      sh "c++ -I../gtest -I../gtest/include -c #{t.prerequisites.first}"
    end
  end

  file 'gtest_main.a' => gtest_sources.map(&dot_o) do |t|
    sh "ar -rv #{t.name} #{t.prerequisites.join ' '}"
  end

  for source in test_sources
    file dot_o[source] => "test/#{source}.cc" do |t|
      sh "c++ -c -I. -Itest -I../gtest/include #{t.prerequisites.first}"
    end
  end

  for source in sources
    file dot_o[source] => "#{source}.cpp" do |t|
      sh "c++ -c -Itest #{t.prerequisites.first}"
    end
  end

  file 'test/test' => (sources + test_sources).map(&dot_o) + %w[gtest_main.a] do |t|
    sh "c++ -o #{t.name} #{t.prerequisites.join ' '}"
  end

  task all: "test/test" do |t|
    sh "./#{t.prerequisites.first}"
  end

  task :clean do
    sh "rm *.o test/test"
  end
end

task default: 'test:all'
